### ISSUE TITLE
$restart command

### ISSUE THREAD

**Issue by satanicsanta** [satanicsanta/SatanicBot#26]
Like the $quit command, but will start it again.

**Comment by Strikingwolf** [comment]
@satanicsanta I have no idea how this would work :laughing:

**Comment by satanicsanta** [comment]
I don't either. I would probably need to make it do some command-line stuff, possibly in Shell or something.

**Comment by Strikingwolf** [comment]
yeah, I also don't know how I could take the input I do with my bot

**Comment by satanicsanta** [comment]
I do no command-line input with my bot.

**Comment by satanicsanta** [comment]
@Strikingwolf you could just remember the input you gave it when you first ran it and use that, rather than redoing the whole thing. If that makes sense.

**Comment by Strikingwolf** [comment]
Meh, the restart command isn't that important to me so it isn't that bad

**Comment by satanicsanta** [comment]
I no longer care for this feature.
