### ISSUE TITLE
Add $delquote command

### ISSUE THREAD

**Issue by KamranMackey** [satanicsanta/SatanicBot#44]
Add command which removes quotes from the quote list.

**Comment by satanicsanta** [comment]
I don't see why this would ever be useful.

**Comment by KamranMackey** [comment]
@satanicsanta It's useful for when somebody would want to remove a quote, such as some of my quotes. :stuck_out_tongue_winking_eye:

**Comment by satanicsanta** [comment]
Nah. You can just politely ask me, and I might do it.
